package observability

import (
	"strconv"
	"sync/atomic"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/prometheus/client_golang/prometheus"
)

var (
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests.",
		},
		[]string{"method", "route", "status"},
	)

	httpRequestDurationSeconds = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "HTTP request duration in seconds.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "route", "status"},
	)

	httpRateLimit429Total = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_rate_limit_429_total",
			Help: "Total number of HTTP 429 responses generated by rate limiting.",
		},
		[]string{"method", "route"},
	)

	rateLimit429Snapshot uint64
)

func init() {
	prometheus.MustRegister(httpRequestsTotal)
	prometheus.MustRegister(httpRequestDurationSeconds)
	prometheus.MustRegister(httpRateLimit429Total)
}

// PrometheusMiddleware captures request count and duration metrics.
func PrometheusMiddleware() fiber.Handler {
	return func(c *fiber.Ctx) error {
		start := time.Now()
		err := c.Next()

		status := c.Response().StatusCode()
		if err != nil && status == 0 {
			status = fiber.StatusInternalServerError
		}

		route := c.Path()
		if c.Route() != nil && c.Route().Path != "" {
			route = c.Route().Path
		}

		labels := []string{c.Method(), route, strconv.Itoa(status)}
		httpRequestsTotal.WithLabelValues(labels...).Inc()
		httpRequestDurationSeconds.WithLabelValues(labels...).Observe(time.Since(start).Seconds())
		if status == fiber.StatusTooManyRequests {
			httpRateLimit429Total.WithLabelValues(c.Method(), route).Inc()
			atomic.AddUint64(&rateLimit429Snapshot, 1)
		}

		return err
	}
}

// RateLimitMetricsHandler exposes a simple operational snapshot for quick checks.
func RateLimitMetricsHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"rate_limit_429_total": atomic.LoadUint64(&rateLimit429Snapshot),
	})
}
